// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfygAUsKKrzRsE72IAhjWXfYW0l_bw6fs',
    appId: '1:227274581506:web:8d42b7471afcedbda8e91b',
    messagingSenderId: '227274581506',
    projectId: 'flutter-auth-firestore-app',
    authDomain: 'flutter-auth-firestore-app.firebaseapp.com',
    storageBucket: 'flutter-auth-firestore-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMuCDoblkw0wlj3U2Ag_BKq3CQ6Jrjtv4',
    appId: '1:227274581506:android:f3b2a8dc0ef835a5a8e91b',
    messagingSenderId: '227274581506',
    projectId: 'flutter-auth-firestore-app',
    storageBucket: 'flutter-auth-firestore-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiOpfbvf7XYqgvMOSSOJpbVLy9YbR1Tqg',
    appId: '1:227274581506:ios:cb98e392670bb0c2a8e91b',
    messagingSenderId: '227274581506',
    projectId: 'flutter-auth-firestore-app',
    storageBucket: 'flutter-auth-firestore-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiOpfbvf7XYqgvMOSSOJpbVLy9YbR1Tqg',
    appId: '1:227274581506:ios:cb98e392670bb0c2a8e91b',
    messagingSenderId: '227274581506',
    projectId: 'flutter-auth-firestore-app',
    storageBucket: 'flutter-auth-firestore-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfygAUsKKrzRsE72IAhjWXfYW0l_bw6fs',
    appId: '1:227274581506:web:1b90d7875d8740aaa8e91b',
    messagingSenderId: '227274581506',
    projectId: 'flutter-auth-firestore-app',
    authDomain: 'flutter-auth-firestore-app.firebaseapp.com',
    storageBucket: 'flutter-auth-firestore-app.firebasestorage.app',
  );
}
